version: '3'
services:
  app:
    image: observability/tcc
    environment:
      OTEL_SERVICE_NAME: "custom-annotation"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4318"
    ports:
      - "8080:8080"
    depends_on:
      - collector

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  collector:
    image: otel/opentelemetry-collector-contrib:0.99.0
    volumes:
      - ./otel-config.yaml:/otel-config.yaml
    command: ["--config=/otel-config.yaml"]
    expose:
      - "4318"
    ports:
      - "4318:4318"
      - "8888:8888"
      - "8889:8889"
