receivers:
  hostmetrics:
    collection_interval: 1.9s
    scrapers:
      cpu:
      memory:
      load:
      network:
  otlp:
    protocols:
      http:
processors:
  filter:
    error_mode: ignore
    traces:
      span:
        - attributes["server.address"] == "172.17.0.1"
exporters:
  logging:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlp:
    endpoint: "http://jaeger:4317"
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [otlp, hostmetrics]
      processors: []
      exporters: [logging, prometheus]
    traces:
      receivers: [otlp]
      processors: [filter]
      exporters: [logging, otlp]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [logging]
